config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :friendships, only: [:index, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  # Defines the root path route ("/")
  root "users#show"
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, :post_id, presence: true
  validates :user_id, :post_id, numericality: { only_integer: true }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :people_who_liked, through: :likes, source: :user
  has_many :comments

  def liked_by? current_user
    !likes.find_by(user_id: current_user.id).nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :likes, dependent: :destroy

  after_create :send_welcome_email

  def send_welcome_email
    SignupMailer.with(user: self).welcome_email.deliver_later
  end

  def pending_friend_requests
    friends.reject { |friend| friend.friends.include? self }
  end

  def active_friends
    friends.select { |friend| friend.friends.include? self }
  end

  def requests_to_accept
    Friendship.where(friend_id: id).map { |friendship| User.find(friendship.user_id) }.reject { |user| active_friends.include? user }
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  @@post_id_param = 0

  def new
    @comment = Comment.new
    @@post_id_param = comment_post_id_params
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = @@post_id_param[:post_id]
    if @comment.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_post_id_params
    params.require(:comment).permit(:post_id)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  def create
    @user = User.find(friendship_params[:friend_id])

    if current_user.friends.include?(@user) || current_user == @user
      flash[:notify] = "Already friends with #{@user.name}"
      @users = User.all
    else
      Friendship.create(user_id: current_user.id, friend_id: friendship_params[:friend_id])
      @users = User.all
    end
    redirect_to users_path
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship2 = Friendship.find_by(user_id: @friendship.friend_id, friend_id: current_user.id)
    @friendship.delete
    @friendship2.delete unless @friendship2.nil?

    flash[:success] = "#{User.find(@friendship.friend_id).name} is not a friend anymore"
    redirect_to users_path, status: :see_other
  end

  private

  def friendship_params
    params.require(:friendship).permit(:friend_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  def create
    @like = current_user.likes.build(post_params)
    if Like.find_by(user_id: current_user.id, post_id: post_params[:post_id]).nil?
      if @like.save
        redirect_to posts_path, notice: 'Post liked'
      else
        redirect_to current_user, status: :unprocessable_entity
      end
    end
  end

  def destroy
    if Like.find(params[:id]).delete
      redirect_to posts_path, notice: 'Unliked post'
    else
      redirect_to posts_path, status: :unprocessable_entity
    end
  end

  def post_params
    params.require(:post).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    posts = current_user.posts
    friends_posts = current_user.friends.map { |friend| friend.posts }.flatten
    @all_posts = (posts + friends_posts).sort_by(&:created_at).reverse
  end

  def new
    @post = Post.new
  end

  def create
    if current_user.posts.build(post_params).save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    # profile information, photo and posts
    @user = param_user_id ? User.find(param_user_id) : current_user
    @gravatar_url = gravatar_url @user.email
  end

  def index
    # list all users and buttons for sending friend requests
    @users = User.all
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(edit_params)
      redirect_to user_path, notice: 'Updated information'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def param_user_id
    params.permit(:id)[:id]
  end

  def edit_params
    params.require(:user).permit(:name, :email, :birthday, :city, :employment, :education)
  end

  def gravatar_url(email)
    "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest email.downcase}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= link_to "back", current_user %>

<%= form_with model: @comment, url: comments_path do |form| %>
  <div class="new-post-form">
    <%= form.label :content %>
    <%= form.text_area :content %>
    <br>
    <%= form.submit 'Submit' %>

  </div>
<% end %>

app/views/friendships/index.html.erb
<h1>Friends</h1>

<%= render 'users/nav' %>

<h2>Pending</h2>
<% current_user.pending_friend_requests.each do |friend| %>
  <%= friend.name %>
<% end %>

<h2>Active</h2>
<% current_user.active_friends.each do |friend| %>
  <%= friend.name %>
<% end %>

<h2>Requests</h2>
<% current_user.requests_to_accept.each do |user| %>
  <%= user.name %>
  <%= link_to 'Accept', friendships_path + "?[friendship]friend_id=#{user.id}", data:{turbo_method: :post, turbo_confirm: "Really accept #{user.name} as friend", friendship: [12]} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <div class="flash">
    <p style="color:green"><%= msg %></p>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="posts">
<h1>Posts</h1>

<%= render 'users/nav' %>

<div class="new_post">
  <%= link_to "New Post", new_post_path %>
</div>

  <% render 'flash_message' %>

  <% @all_posts.each do |post| %>
    <hr>
    <div class="post">
      
      <div class="post-head">
        <p class="user-name"><%= post.created_at %></p>
        <p class="user-name"><%= post.user.name %></p>
      </div>
      <div class="post-body">
        <p class="post-title"><%= post.title %></p>
        <div class="post-content"><%= post.content %></div>
      </div>
      <div class="footer">
        <%= "Likes: #{post.likes.count}" %>
        <% if !post.liked_by? current_user %>
          <p class="post-like">
            <%= form_with model: post, url: likes_path, method: 'post' do |form| %>
              <%= form.hidden_field 'post_id', value: post.id %>
              <%= form.submit 'Like' %>
            <% end %>
          </p>
        <% else %>
          <p class="post-unlike">
            <%= form_with model: post, url: like_path(post.likes.find_by(user_id: current_user.id)), method: 'delete' do |form| %>
              <%= form.submit 'Unlike' %>
            <% end %>
          </p>
        <% end %>
      </div>
      <%= form_with model: post.comments, url: new_comment_path, method: 'GET' do |form| %>
        <%= form.hidden_field 'post_id', value: post.id %>
        <%= form.submit 'Comment' %>
      <% end %>
    </div>

    <% unless post.comments.empty? %>
      <div class="comments">
        <p><strong>Comments</strong></p>
        <% post.comments.each do |comment| %>
          <%= comment.user.name %>
          <br>
          <%= comment.content %>
          <br>
        <% end %>
      </div>
    <% end %>
    
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= link_to "back", current_user %>

<%= form_with model: @post do |form| %>
  <div class="new-post-form">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :content %>
    <%= form.text_area :content %>
    <br>
    <%= form.submit %>

  </div>
<% end %>

app/views/users/_nav.html.erb
<div class="nav">
  <ul>
    <li><%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %></li>
    <li><%= link_to 'Profile', current_user %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to "Friend requests (#{current_user.requests_to_accept.count})", friendships_path %></li>
    <li><%= link_to "Posts", posts_path %></li>
  </ul>
</div>

app/views/users/_posts.html.erb
<div class="posts">
<h3>Posts</h3>
  <div class="new_post">
    <%= link_to "New Post", new_post_path %>
  </div>
  <% @user.posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <img src=<%= @gravatar_url %> alt="profile photo" width="64" height="64" style="border-radius: 50%">
        <p class="user-name"><%= @user.name %></p>
      </div>
      <div class="post-body">
        <p class="post-title"><%= post.title %></p>
        <div class="post-content"><%= post.content %></div>
      </div>
      <div class="footer">
        <%= "Likes: #{post.likes.count}" %>
        <p class="post-like">
          <%= form_with model: post, url: likes_path, method: 'post' do |form| %>
            <%= form.hidden_field 'post_id', value: post.id %>
            <%= form.submit 'Like' %>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit personal information</h1>

<div>
  <%= form_with model: @user do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br>
    <%= form.label :email %>
    <%= form.text_field :email %>
    <br>
    <%= form.label :birthday %>
    <%= form.date_field :birthday %>
    <br>
    <%= form.label :city %>
    <%= form.text_field :city %>
    <br>
    <%= form.label :employment %>
    <%= form.text_field :employment %>
    <br>
    <%= form.label :education %>
    <%= form.text_field :education %>
    <br>

    <%= form.submit 'Update' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<%= render 'users/nav' %>

<div class="user-list">
  <% @users.each do |user|%>
    <div>
      <div><strong><%= link_to user.name, user_path(user) %></strong></div>
      <% if current_user != user %>
        <% if !current_user.friends.include? user %>
          <%= form_with url: friendships_path do |form| %>
            <%= form.hidden_field '[friendship]friend_id', value: user.id %>
            <%= form.submit 'Add friend' %>
          <% end %>
        <% else %>
          <p>(Friend)</p>
          <%= link_to 'Remove friend', "friendships/#{Friendship.find_by(user_id: current_user.id, friend_id: user.id).id}", data:{turbo_method: :delete, turbo_confirm: "Really unfriend #{user.name}?"} %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Profile</h1>

<%= render "flash_message" %>

<%= render "nav" %>

<div class="photo">
  <img src=<%= @gravatar_url %> alt="profile photo" width="64" height="64" style="border-radius: 50%">
</div>

<div class="information">
  <p class="name">Name: <%= @user.name %></p>
  <p class="email">Email: <%= @user.email %></p>
  <p class="birthday">Birthday: <%= @user.birthday %></p>
  <p class="city">City: <%= @user.city %></p>
  <p class="employment">Employment: <%= @user.employment %></p>
  <p class="education">Education: <%= @user.education %></p>
  <%= link_to 'Edit', edit_user_path(current_user.id) %>
</div>